server:
  port: 8085
rocketmq:
  name-server: localhost:9876
  producer:
    group: trans_producer_group
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/springbootstudy?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  configuration:
    map-underscore-to-camel-case: true